CREATE TABLE IF NOT EXISTS countries (
    id UUID NOT NULL DEFAULT uuid_generate_v4 (),
    iso VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    iso3 VARCHAR NOT NULL,
    numcode VARCHAR NOT NULL,
    phonecode VARCHAR NOT NULL,
    currency VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT "primary" PRIMARY KEY (id)
);